---
- import_tasks: homebrew.yml
- import_tasks: sublime_text.yml

- name: 'Disable Dashboard'
  shell: defaults write com.apple.dashboard mcx-disabled -bool true

- name: 'Save screenshots to Downloads'
  shell: defaults write com.apple.screencapture location ~/Downloads
